// File generated by flutterfire_cli.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// A class that exposes all available Firebase options.
class DefaultFirebaseOptions {
  /// `ProjectId` in Firebase console
  static const String projectId = 'spendmate-budget-tracker';

  static const FirebaseOptions currentPlatform = android;

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1JhVYu6QI8VgF9q4qQ4lBmXx8nN8bZ8I',
    appId: '1:887808188942:android:f51e7f22a3bb765d69525f',
    messagingSenderId: '887808188942',
    projectId: 'spendmate-budget-tracker',
    databaseURL: 'https://spendmate-budget-tracker.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmU8XZxM9QZ8jQp0qLq8VYu2N3pN0qL4I',
    appId: '1:887808188942:ios:2f32a3956b9a610369525f',
    messagingSenderId: '887808188942',
    projectId: 'spendmate-budget-tracker',
    databaseURL: 'https://spendmate-budget-tracker.firebaseio.com',
    iosBundleId: 'com.example.pixie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmU8XZxM9QZ8jQp0qLq8VYu2N3pN0qL4I',
    appId: '1:887808188942:ios:2f32a3956b9a610369525f',
    messagingSenderId: '887808188942',
    projectId: 'spendmate-budget-tracker',
    databaseURL: 'https://spendmate-budget-tracker.firebaseio.com',
    iosBundleId: 'com.example.pixie',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0qZ8nL7pR2sT5uV9wX3yZ1aB4cD6eF8gH',
    appId: '1:887808188942:web:07bc83049a168e4b69525f',
    messagingSenderId: '887808188942',
    projectId: 'spendmate-budget-tracker',
    authDomain: 'spendmate-budget-tracker.firebaseapp.com',
    databaseURL: 'https://spendmate-budget-tracker.firebaseio.com',
    storageBucket: 'spendmate-budget-tracker.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0qZ8nL7pR2sT5uV9wX3yZ1aB4cD6eF8gH',
    appId: '1:887808188942:web:1dab459be6e7704b69525f',
    messagingSenderId: '887808188942',
    projectId: 'spendmate-budget-tracker',
    authDomain: 'spendmate-budget-tracker.firebaseapp.com',
    databaseURL: 'https://spendmate-budget-tracker.firebaseio.com',
    storageBucket: 'spendmate-budget-tracker.appspot.com',
  );
}
