// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQdEuRmeGWBx5lrCx3qYWGWSxcYi5U3uM',
    appId: '1:19083732054:web:666e9adbda396164aec7f7',
    messagingSenderId: '19083732054',
    projectId: 'pixie-adff5',
    authDomain: 'pixie-adff5.firebaseapp.com',
    databaseURL: 'https://pixie-adff5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pixie-adff5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAid0VAxuzzIdhD587-Fzn6WFCzxAG6T_c',
    appId: '1:19083732054:android:c39934f7127e9156aec7f7',
    messagingSenderId: '19083732054',
    projectId: 'pixie-adff5',
    databaseURL: 'https://pixie-adff5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pixie-adff5.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQdEuRmeGWBx5lrCx3qYWGWSxcYi5U3uM',
    appId: '1:19083732054:web:612b0641c59b53c2aec7f7',
    messagingSenderId: '19083732054',
    projectId: 'pixie-adff5',
    authDomain: 'pixie-adff5.firebaseapp.com',
    databaseURL: 'https://pixie-adff5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pixie-adff5.firebasestorage.app',
  );
}
