// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl3c5M--nzH8c2yWdWKqZS7GNU86c6eGI',
    appId: '1:887808188942:web:07bc83049a168e4b69525f',
    messagingSenderId: '887808188942',
    projectId: 'spendmate-budget-tracker',
    authDomain: 'spendmate-budget-tracker.firebaseapp.com',
    storageBucket: 'spendmate-budget-tracker.firebasestorage.app',
    measurementId: 'G-SKWHMR5RX5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0X-NsVRth4KzB3jUCrc9e0Sk56fq02jM',
    appId: '1:887808188942:android:f51e7f22a3bb765d69525f',
    messagingSenderId: '887808188942',
    projectId: 'spendmate-budget-tracker',
    storageBucket: 'spendmate-budget-tracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_3GsaohrNNrZGXuZBq-TKA8zbzXcTlcY',
    appId: '1:887808188942:ios:2f32a3956b9a610369525f',
    messagingSenderId: '887808188942',
    projectId: 'spendmate-budget-tracker',
    storageBucket: 'spendmate-budget-tracker.firebasestorage.app',
    iosBundleId: 'com.example.recordExpenses',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_3GsaohrNNrZGXuZBq-TKA8zbzXcTlcY',
    appId: '1:887808188942:ios:2f32a3956b9a610369525f',
    messagingSenderId: '887808188942',
    projectId: 'spendmate-budget-tracker',
    storageBucket: 'spendmate-budget-tracker.firebasestorage.app',
    iosBundleId: 'com.example.recordExpenses',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCl3c5M--nzH8c2yWdWKqZS7GNU86c6eGI',
    appId: '1:887808188942:web:1dab459be6e7704b69525f',
    messagingSenderId: '887808188942',
    projectId: 'spendmate-budget-tracker',
    authDomain: 'spendmate-budget-tracker.firebaseapp.com',
    storageBucket: 'spendmate-budget-tracker.firebasestorage.app',
    measurementId: 'G-D9JMXPYM70',
  );

}